version: '3'

services:
  rust-service:
    image: vbulavintsev/meritrank-service-rust:latest
    ports:
      - '10234:10234'
    depends_on:
      - postgres-tentura

  postgres-tentura:
    image: vbulavintsev/postgres-tentura:latest
    ports:
      - '15432:5432' # temp
    volumes:
      - '/home/shestero/.pgrx/16.1/pgrx-install/lib/postgresql/pgmer2.so:/usr/lib/postgresql/16/lib/pgmer2.so'
      - '/home/shestero/.pgrx/16.1/pgrx-install/share/postgresql/extension/pgmer2.control:/usr/share/postgresql/16/extension/pgmer2.control'
      - '/home/shestero/.pgrx/16.1/pgrx-install/share/postgresql/extension/pgmer2--0.1.0.sql:/usr/share/postgresql/16/extension/pgmer2--0.1.0.sql'

  hasura:
    image: hasura/graphql-engine
    ports:
      - '8080:8080'
    environment:
      - "HASURA_GRAPHQL_DATABASE_URL=postgres://postgres-tentura:15432/pgmer2"
      - "HASURA_GRAPHQL_ENABLE_CONSOLE=true"



