[package]
name = "start"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
serde = "1.0.166"
serde_derive = "1.0.166"
nng = "1.0.1"
rmp-serde = "1.1.2"
reflection = "0.1.3"
reflection_derive = "0.1"
rayon = "1.8.0"
postgres = "0.19.7"