name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        export MERITRANK_NUM_WALK=50
        cargo test
  docker_build:
    needs: [ build_and_test ]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Determine tag
      shell: bash
      run: |
        export VER="v0.2"
        export N=17
        while [ $(docker manifest inspect vbulavintsev/meritrank-service:$VER.$N >/dev/null 2>&1; echo $?) -eq 0 ]; do
          let N++
        done
        echo "TAG=$VER.$N" >> $GITHUB_ENV
    - name: Build docker image
      run: |
        docker build -t vbulavintsev/meritrank-service:$TAG .
    - name: Push docker image to Dockerhub
      if: ${{ github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        docker login -u vbulavintsev -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker image push vbulavintsev/meritrank-service:$TAG
