name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        export RUST_TEST_THREADS=1
        export NUM_WALK=50
        export GRAVITY_NUM_WALK=50
        cargo test
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: |
        docker build -t meritrank-service:dev .
        docker image save meritrank-service:dev -o meritrank_service_dev.tar
    - name: Upload docker image
      uses: actions/upload-artifact@v4
      with:
        name: meritrank_service_dev.tar
        path: meritrank_service_dev.tar
        retention-days: 2
