name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        export RUST_TEST_THREADS=1
        export MERITRANK_NUM_WALK=50
        cargo test
  docker_build:
    needs: [ build_and_test ]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: |
        docker build -t vbulavintsev/meritrank-service:dev .
        docker image save vbulavintsev/meritrank-service:dev -o meritrank_service_dev.tar
    - name: Push docker image to Dockerhub
      if: ${{ github.ref == 'refs/heads/dev' }}
      shell: bash
      run: |
        export VER="dev-$(date +'%Y-%m')"
        export N=1
        while [ $(docker manifest inspect vbulavintsev/meritrank-service:$VER-$N >/dev/null 2>&1; echo $?) -eq 0 ]; do
          let N++
        done
        docker login -u vbulavintsev -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker image push vbulavintsev/meritrank-service:$VER-$N
    - name: Upload docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: meritrank_service_dev.tar
        path: meritrank_service_dev.tar
        retention-days: 2
